<a href="https://colab.research.google.com/github/harshshah25/pytorch_basics/blob/main/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(3)
x

tensor([7.4110e+00, 4.3307e-41, 7.4103e+00])

In [4]:
x = torch.empty(2, 3)
print(x)

tensor([[2.4178e-18, 3.1360e+27, 7.0800e+31],
        [3.1095e-18, 2.9907e+21, 1.1626e+27]])


In [5]:
x = torch.rand(2, 3)
print(x)

tensor([[0.0294, 0.3408, 0.2388],
        [0.7285, 0.0623, 0.9061]])


In [7]:
x = torch.ones(4, 4, dtype = torch.int)
print(x)
print(x.size())

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
torch.Size([4, 4])


In [8]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [9]:
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [10]:
a += 1
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [11]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.1272, 0.0586],
        [0.2885, 0.4148]])
tensor([[0.1945, 0.2159],
        [0.6330, 0.9644]])


In [12]:
z = x + y
print(z)

tensor([[0.3216, 0.2745],
        [0.9215, 1.3792]])


In [13]:
#Every function which has an underscore in the end will perform an inplace operation in PyTorch
y.add_(x)

tensor([[0.3216, 0.2745],
        [0.9215, 1.3792]])

In [14]:
z = torch.sub(x, y)
z = torch.mul(x, y)
z = torch.div(x, y)

In [15]:
x = torch.rand(5, 3)
print(x)
print(x[3, :])

tensor([[0.2342, 0.0990, 0.3052],
        [0.0571, 0.1390, 0.7562],
        [0.1006, 0.4707, 0.5530],
        [0.6914, 0.1977, 0.8806],
        [0.9156, 0.5333, 0.3494]])
tensor([0.6914, 0.1977, 0.8806])


In [16]:
print(x[1, 1].item())

0.13897037506103516


In [18]:
#Reshaping
x = torch.rand(4, 4)
y = x.view(16)
print(y.size())

y = x.view(-1, 2)
print(y.size())

torch.Size([16])
torch.Size([8, 2])
