In [5]:
pip install torch

In [6]:
import torch

In [13]:
#Create a Tensor
t1 = torch.empty(3)
t1

tensor([ 2.0971e+08,  3.3477e-41, -3.8810e+07])

In [11]:
t1.dtype

torch.float32

In [14]:
t2 = torch.empty(3, dtype = torch.int)
t2

tensor([1298388880,      23890, 1298614736], dtype=torch.int32)

In [15]:
t3 = torch.rand(5, 4, 3)
t3

tensor([[[0.9433, 0.3017, 0.1080],
         [0.8922, 0.6660, 0.4278],
         [0.4913, 0.4716, 0.7162],
         [0.2328, 0.7611, 0.0291]],

        [[0.6427, 0.8113, 0.1435],
         [0.7683, 0.2323, 0.6801],
         [0.4698, 0.3818, 0.1200],
         [0.4138, 0.7633, 0.3577]],

        [[0.1625, 0.2184, 0.9584],
         [0.3190, 0.8168, 0.1474],
         [0.2504, 0.8816, 0.8433],
         [0.8970, 0.6581, 0.2041]],

        [[0.5342, 0.9510, 0.7856],
         [0.8242, 0.5481, 0.6311],
         [0.7163, 0.4224, 0.7762],
         [0.5893, 0.1326, 0.5183]],

        [[0.6770, 0.5246, 0.8517],
         [0.9777, 0.6007, 0.7998],
         [0.8109, 0.6678, 0.2574],
         [0.4212, 0.2145, 0.7734]]])

In [16]:
t3.dtype

torch.float32

In [18]:
t4 = torch.randint(0, 20, [5, 4])
t4

tensor([[ 7, 12,  1, 18],
        [13, 15, 12,  1],
        [15,  1, 17,  5],
        [ 3, 16, 18, 10],
        [ 5,  3, 13, 19]])

In [19]:
t5 = torch.zeros(2, 3)
t5

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
t6 = torch.ones([2, 3, 4], dtype = torch.int)
t6

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)

In [23]:
t6.dtype

torch.int32

In [24]:
t6.size()

torch.Size([2, 3, 4])

In [25]:
t6.dim()

3

In [26]:
import numpy as np

In [27]:
arr = np.ones([2, 3])
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
t7 = torch.tensor(arr)
t7

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [29]:
#Inplace Operator
t8 = torch.ones(2,3, dtype = torch.int)
t8

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [30]:
t9 = torch.ones(2,3, dtype = torch.int)

In [31]:
t10 = torch.add(t8 , t9)

In [32]:
t10

tensor([[2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

In [33]:
t9.add_(t8)

tensor([[2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

In [34]:
t9

tensor([[2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)

In [35]:
t9.sub_(t8)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [36]:
#Reshaping the tensors
t7.size()

torch.Size([2, 3])

In [37]:
t7.reshape(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [38]:
#Tensor Broadcasting
t7.size()

torch.Size([2, 3])

In [39]:
t6.size()

torch.Size([2, 3, 4])

In [75]:
# To add:
# equal shapes
# one of the dimensions has to be one.

In [42]:
x = torch.empty(5,4,3,1)

In [43]:
y = torch.empty(1,3,5)

In [44]:
z = torch.add(x, y)

In [45]:
z

tensor([[[[-7.7623e+07, -3.8812e+07,  2.0890e+08, -3.8812e+07, -3.8812e+07],
          [ 4.3313e-41,  4.3470e-41,  4.3313e-41, -2.5637e-24,  7.6797e-41],
          [ 4.5401e+08,  2.4404e+08,  2.8274e+08,  2.4404e+08,  2.4404e+08]],

         [[-3.8811e+07,  7.6790e-41,  2.4772e+08,  6.6954e-41,  3.3522e-41],
          [ 4.4842e-44,  2.0179e-43,  4.4842e-44, -2.5637e-24,  3.3529e-41],
          [ 2.0997e+08,  3.3477e-41,  3.8701e+07,  3.3477e-41, -2.1899e-33]],

         [[-3.8811e+07,  4.3470e-41,  2.4772e+08,  3.3634e-41,  2.0179e-43],
          [ 0.0000e+00,  1.5695e-43,  0.0000e+00, -2.5637e-24,  3.3484e-41],
          [ 2.0997e+08, -2.5470e-24,  3.8701e+07, -2.5470e-24, -2.5470e-24]],

         [[-3.8811e+07,  7.6797e-41,  2.4772e+08,  6.6961e-41,  3.3529e-41],
          [ 5.3639e-08,  5.3639e-08,  5.3639e-08,  5.3639e-08,  5.3639e-08],
          [ 6.7360e+22,  6.7360e+22,  6.7360e+22,  6.7360e+22,  6.7360e+22]]],


        [[[ 4.1541e+21,  4.1541e+21,  4.1541e+21,  4.1541e+21,  4.

In [46]:
z.size()

torch.Size([5, 4, 3, 5])

In [51]:
#Vector Multiplication
A = torch.tensor([[10, 5, 5, 6]])
B = torch.tensor([[56], [120], [574], [80]])

In [52]:
C = torch.mul(A,B)

In [53]:
C

tensor([[ 560,  280,  280,  336],
        [1200,  600,  600,  720],
        [5740, 2870, 2870, 3444],
        [ 800,  400,  400,  480]])

In [54]:
#Transpose
x = torch.randint(0, 20, [4,5])

In [55]:
x

tensor([[13,  2, 10,  9, 12],
        [17, 11, 11,  9, 11],
        [ 3,  2, 18,  5, 11],
        [ 4,  9,  4,  8, 10]])

In [56]:
x.size()

torch.Size([4, 5])

In [57]:
y = torch.transpose(x, 0, 1)

In [58]:
y.size()

torch.Size([5, 4])

In [59]:
y

tensor([[13, 17,  3,  4],
        [ 2, 11,  2,  9],
        [10, 11, 18,  4],
        [ 9,  9,  5,  8],
        [12, 11, 11, 10]])

In [60]:
#Indexing & Slicing
y

tensor([[13, 17,  3,  4],
        [ 2, 11,  2,  9],
        [10, 11, 18,  4],
        [ 9,  9,  5,  8],
        [12, 11, 11, 10]])

In [62]:
y[0][0].item()

13

In [63]:
t13 = torch.rand(5,4,7)

In [64]:
t13

tensor([[[0.6863, 0.5250, 0.4418, 0.6228, 0.3498, 0.1790, 0.3991],
         [0.3900, 0.7282, 0.3445, 0.6651, 0.2682, 0.7359, 0.8455],
         [0.0891, 0.3389, 0.9752, 0.7765, 0.7043, 0.9205, 0.3741],
         [0.7656, 0.8634, 0.1093, 0.8786, 0.4128, 0.5154, 0.9174]],

        [[0.0105, 0.6375, 0.8607, 0.7044, 0.0856, 0.5160, 0.5350],
         [0.4019, 0.7250, 0.1578, 0.2063, 0.1348, 0.4013, 0.8916],
         [0.3743, 0.2834, 0.6497, 0.0680, 0.3457, 0.3595, 0.9763],
         [0.9970, 0.6772, 0.5536, 0.1849, 0.7980, 0.0060, 0.4071]],

        [[0.3278, 0.9616, 0.0132, 0.9604, 0.1443, 0.1845, 0.4549],
         [0.2840, 0.4182, 0.3893, 0.6091, 0.4460, 0.5278, 0.6391],
         [0.0366, 0.3245, 0.1854, 0.7663, 0.8893, 0.5992, 0.2759],
         [0.5291, 0.9314, 0.5188, 0.9592, 0.1242, 0.9263, 0.3844]],

        [[0.0176, 0.3117, 0.6168, 0.6256, 0.4351, 0.4638, 0.4921],
         [0.6663, 0.2387, 0.1020, 0.7301, 0.1710, 0.8307, 0.2013],
         [0.5837, 0.7290, 0.2721, 0.4599, 0.1913, 0.6386

In [66]:
t13[4][3][-1]

tensor(0.1186)

In [67]:
t13[1:3]

tensor([[[0.0105, 0.6375, 0.8607, 0.7044, 0.0856, 0.5160, 0.5350],
         [0.4019, 0.7250, 0.1578, 0.2063, 0.1348, 0.4013, 0.8916],
         [0.3743, 0.2834, 0.6497, 0.0680, 0.3457, 0.3595, 0.9763],
         [0.9970, 0.6772, 0.5536, 0.1849, 0.7980, 0.0060, 0.4071]],

        [[0.3278, 0.9616, 0.0132, 0.9604, 0.1443, 0.1845, 0.4549],
         [0.2840, 0.4182, 0.3893, 0.6091, 0.4460, 0.5278, 0.6391],
         [0.0366, 0.3245, 0.1854, 0.7663, 0.8893, 0.5992, 0.2759],
         [0.5291, 0.9314, 0.5188, 0.9592, 0.1242, 0.9263, 0.3844]]])

In [74]:
#Reverse Indexing

In [69]:
t14 = torch.flip(t13, [0,1])

In [71]:
y

tensor([[13, 17,  3,  4],
        [ 2, 11,  2,  9],
        [10, 11, 18,  4],
        [ 9,  9,  5,  8],
        [12, 11, 11, 10]])

In [72]:
y = torch.flip(y, [0,1])

In [73]:
y

tensor([[10, 11, 11, 12],
        [ 8,  5,  9,  9],
        [ 4, 18, 11, 10],
        [ 9,  2, 11,  2],
        [ 4,  3, 17, 13]])